#!/usr/bin/python
#
# t1make: a script to generate test images t1.vx and t1.vd
#   also used are t1-tmp1 and  t1-tmp2
#
import os
bbx="0,20,0,20,0,20"
os.system( "vgen3d e=12,12,12 bb=" + bbx + "  tr=10,10,10 of=t1-tmp1")
os.system( "vgen3d p=3,3,15 bb=" + bbx + " tr=10,10,10 of=t1-tmp2")
os.system( "vop -or t1-tmp1 t1-tmp2 | vdim -c -o t1.vx")
os.system( "v3pol -t t1.vx -o t1.vd")
os.system( "rm t1-tmp1 t1-tmp2")
